### ISSUE TITLE
Factorial Program 

### ISSUE THREAD

**Issue by Sjsingh101** [Sjsingh101/Basic-C-Programs#1]

**Comment by anmolagarwal999** [comment]
Can I do this as a part of HacktoberFest 2019 ?

**Comment by jaywantpatel** [comment]
I want to contribute

**Comment by theNitishSoni** [comment]
#include<iostream>
using namespace std;
class fact
{
    int n,sum=1;
public:
    void getdata()
    {
        cin>>n;
    }
    void factorial()
    {
        for(int i=n;i>=1;i--)
        {
            sum=sum*i;
        }
    }
    void putdata()
    {
        cout<<sum<<endl;
    }
};
int main()
{
    fact obj;
    obj.getdata();
    obj.factorial();
    obj.putdata();
}

**Comment by Hitanshu123** [comment]
Is this issue still open ?

**Comment by Sjsingh101** [comment]
@Hitanshu123 yes for documentation and factorials iterative approach
