### ISSUE TITLE
Bubble Sort Program

### ISSUE THREAD

**Issue by Sjsingh101** [Sjsingh101/Basic-C-Programs#3]

**Comment by anmolagarwal999** [comment]
Can I do this as a part of HacktoberFest 2019 ?

**Comment by Kuljeet-123** [comment]
I would like to contribute.

**Comment by jaywantpatel** [comment]
I want to work on this

**Comment by Sjsingh101** [comment]
This issue is still open for beginners who can provide documentation explaing each line of code in a markdown file

**Comment by Zircoz** [comment]
@Sjsingh101 I would love to do that.

**Comment by Zircoz** [comment]
> 
> 
> This issue is still open for beginners who can provide documentation explaing each line of code in a markdown file

I would love to do that.

**Comment by Sjsingh101** [comment]
@Zircoz Waiting for an awesome documentation by you

**Comment by Zircoz** [comment]
> 
> 
> @Zircoz Waiting for an awesome documentation by you

@Sjsingh101 Done, created PR
