### ISSUE TITLE
Binary Search Program

### ISSUE THREAD

**Issue by Sjsingh101** [Sjsingh101/Basic-C-Programs#7]

**Comment by anmolagarwal999** [comment]
Can I do this as a part of HacktoberFest 2019 ?

**Comment by akshaydmc** [comment]
@Sjsingh101  Check the pull request that I created.

**Comment by jaywantpatel** [comment]
Can i take this up ?

**Comment by Deepansharora27** [comment]
Hello !! I am Working on This

**Comment by Sjsingh101** [comment]
Please refer the issue number in PR or i will not be able to merge your request

**Comment by Hitanshu123** [comment]
Hi ! Can I take up this issue ?

**Comment by Hitanshu123** [comment]
Binary_Search.txt #28 . I have made this PR . Please review it . Thank You !

**Comment by Sjsingh101** [comment]
@Hitanshu123 PR of @AkkiBond is already merged you can add documentation explaining this algo in markdown and add PR

**Comment by Hitanshu123** [comment]
@Sjsingh101 I have added the Explanation of Binary Search Algo. Please Review it and Merge it. Thank You !
